mongo-store:
  name: cd-zen-platform-development
  host: 127.0.0.1
  port: 27017
postgresql-store:
  name: 'cd-zen-platform-development'
  host: '127.0.0.1'
  port: 5432
  username: 'platform'
  password: 'QdYx3D5y'
transport:
  type: web
  web:
    host: 0.0.0.0
    port: 10301
